const GET_PLAYER_RANKINGS_STARTED = "GET_PLAYER_RANKINGS_STARTED";
const GET_PLAYER_RANKINGS_SUCCESS = "GET_PLAYER_RANKINGS_SUCCESS";
const GET_PLAYER_RANKINGS_FAILURE = "GET_PLAYER_RANKINGS_FAILURE";

export {
  GET_PLAYER_RANKINGS_STARTED,
  GET_PLAYER_RANKINGS_SUCCESS,
  GET_PLAYER_RANKINGS_FAILURE
};